name: Update Stack
on:
  push:
    branches:
      - master
    paths:
      - 'cloudformation/*'

jobs:
  deploy-cloudformation:
    runs-on: ubuntu-latest
    steps:
    - uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: trent-lab
        template: cloudformation/template.json

