name: Update Stack
on:
  push:
    branches:
      - master
    paths:
      - 'cloudformation/*'
      - .github/workflows/cloudformation.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Load AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy App Stack
        id: deploy
        uses: tnielsen2/cfn-deploy@v2.1.0
        with:
          stackName: trent-lab
          templateFile: cloudformation/template.json
          capabilities: CAPABILITY_NAMED_IAM

