name: Update Lambda
on:
  push:
    branches:
      - master
    paths:
      - 'lambda/*'
      - '.github/workflows/lambda.yml'

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@master
    - name: Configure Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.ptyhon-version }}
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
                  pip install -r requirements.txt
    - name: Run unit tests
      run: |
        python3 -m unittest lambda/test_index.py
    - name: Zip lambda
      run: cd lambda && zip lambda.zip index.py
    - name: Upload to AWS
      uses: yvesgurcan/deploy-lambda-function@master
      with:
        package: ./lambda/lambda.zip
        function-name: trent-lab-function-17WZBUUQ30VQH
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}