name: Update Lambda
on:
  push:
    branches:
      - master
    paths:
      - 'lambda/*'
      - '.github/workflows/lambda.yml'

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: cd lambda && zip lambda.zip index.py
    - uses: yvesgurcan/deploy-lambda-function@master
      with:
        package: ./lambda/lambda.zip
        function-name: trent-lab-function-17WZBUUQ30VQH
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}